# Generated by Django 3.2.9 on 2022-01-20 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_order_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 18, 39, 50, 966660)),
        ),
    ]
